[package]
name = "imaptest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imap = "2.4.1"
mail-parser = "0.8.2"
native-tls = "0.2.11"
